### ISSUE TITLE
Operation Not Supported

### ISSUE THREAD

**Issue by AIC8** [mi5hmash/LimebrellaSharp#12]
Trying to resign RE4R save files and keep getting error message saying Unhandled Exception.. Putting in the right Steam32Ids and imputing the right win64_save folder.   Any Ideas?

**Comment by mi5hmash** [comment]
Hi, could you send the file that you try to resign and the log file from Limebrella Sharp folder? You can sent them to my email address and I will look them after work.

**Comment by AIC8** [comment]
ok Sent

**Comment by mi5hmash** [comment]
@AIC8, thanks. I investigated the log and the file itself and I've responded to your email.
On my computer everything worked without a problem.
The log file you have provided, showed that Limebrella did not reach the file read stage. It's hard to say conclusively what this is caused by.
Maybe the directory you want to load the file from is blocked or the antivirus is blocking Limebrella from reading the file.
I offered to resign the rest of the files for you.

**Comment by AIC8** [comment]
Hey, tried everything.. sent the other 11 files. really appreciate it.. Thank You

**Comment by mi5hmash** [comment]
Hey, I have not received any other files. :( 
Maybe attachments exceeded the maximum size. 
I've created a special container for you on my [dropbox](https://www.dropbox.com/request/TFMHKyC8LlSpO0lZf0qO).

**Comment by AIC8** [comment]
Resent. Thanks

**Comment by mi5hmash** [comment]
[Here](https://www.dropbox.com/scl/fo/l1qtv06l27z2lgiej6d7u/ALmQ_BBXieaZrNiASvAmtQQ?rlkey=mx2t91e2wkjcz4e0xq28hdf1o&st=3qls6qpw&dl=0) you have them. :)

Remember that if your game won't see these files, then you must reach the first typewriter machine and create a save in each save slot.
After that, you can overwrite these save files with the one I resigned for you and relaunch the game. :)

**Comment by AIC8** [comment]
Worked Perfect! You're Awesome.. Thank you soo much

**Comment by mi5hmash** [comment]
Have fun! 😁
